import numpy as np
import matplotlib.pyplot as plt

plt.figure()
plt.subplot(1,2,1)
plt.gca().set_title('Solución Explícita')
data_1 = np.loadtxt("explicit_1.dat")
data_01 = np.loadtxt("explicit_01.dat")
data_001 = np.loadtxt("explicit_001.dat")
plt.plot(data_1[:,0][:-1], data_1[:,1][:-1], label="Delta = " + str(data_1[:,0][-1]))
plt.plot(data_01[:,0][:-1], data_01[:,1][:-1], label="Delta = " + str(data_01[:,0][-1]))
plt.plot(data_001[:,0][:-1], data_001[:,1][:-1], label="Delta = " + str(data_001[:,0][-1]))
plt.xlabel('t')
plt.ylabel('Y')
plt.legend()

plt.subplot(1,2,2)
plt.gca().set_title('Solución Implícita')
data_1 = np.loadtxt("implicit_1.dat")
data_01 = np.loadtxt("implicit_01.dat")
data_001 = np.loadtxt("implicit_001.dat")
plt.plot(data_1[:,0][:-1], data_1[:,1][:-1], label="Delta = " + str(data_1[:,0][-1]))
plt.plot(data_01[:,0][:-1], data_01[:,1][:-1], label="Delta = " + str(data_01[:,0][-1]))
plt.plot(data_001[:,0][:-1], data_001[:,1][:-1], label="Delta = " + str(data_001[:,0][-1]))
plt.xlabel('t')
plt.ylabel('Y')
plt.legend()
plt.tight_layout()
plt.savefig("figura.png")