import numpy as np
import matplotlib.pyplot as plt

plt.figure()
data_1 = np.loadtxt("explicit_1.dat")
data_01 = np.loadtxt("explicit_01.dat")
data_001 = np.loadtxt("explicit_001.dat")
plt.plot(data_1[:,0], data_1[:,1])
plt.plot(data_01[:,0], data_01[:,1])
plt.plot(data_001[:,0], data_001[:,1])
plt.axis('square')
plt.xlabel('X')
plt.ylabel('Y')
plt.savefig("explicit.png")

plt.figure()
data_1 = np.loadtxt("implicit_1.dat")
data_01 = np.loadtxt("implicit_01.dat")
data_001 = np.loadtxt("implicit_001.dat")
plt.plot(data_1[:,0], data_1[:,1])
plt.plot(data_01[:,0], data_01[:,1])
plt.plot(data_001[:,0], data_001[:,1])
plt.axis('square')
plt.xlabel('X')
plt.ylabel('Y')
plt.savefig("implicit.png")